name: tests
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run lint
